{ config, lib, pkgs, niriTheming, niriScripts, ... }:

# niri's own config. There is no home-manager module for niri, so this is
# written out as a KDL file.
#
# Syntax was checked against niri 26.04's parser (niri-config/src/lib.rs) and
# its shipped default-config.kdl rather than from memory — KDL node and
# property names have moved between releases.
let
  inherit (niriTheming) activeDir;

  bin = pkg: lib.getExe pkg;

  # Per-host display layout, from local.niri.outputs. Empty on hosts that
  # don't set it, which leaves niri to auto-detect.
  renderOutput =
    o:
    let
      lines =
        lib.optional o.off "off"
        ++ lib.optional (o.mode != null) ''mode "${o.mode}"''
        ++ lib.optional (o.scale != null) "scale ${toString o.scale}"
        ++ lib.optional (o.transform != null) ''transform "${o.transform}"''
        ++ lib.optional (o.position != null)
          "position x=${toString o.position.x} y=${toString o.position.y}"
        ++ lib.optional o.variableRefreshRate "variable-refresh-rate"
        ++ lib.optional o.focusAtStartup "focus-at-startup";
    in
    ''
      output "${o.name}" {
      ${lib.concatMapStringsSep "\n" (l: "    ${l}") lines}
      }
    '';

  outputBlocks = lib.concatMapStringsSep "\n" renderOutput config.local.niri.outputs;

  workspaceNames = [ "1" "2" "3" ];

  workspaceBlocks = lib.concatMapStringsSep "\n" (
    n:
    if config.local.niri.workspaceOutput == null then
      ''workspace "${n}"''
    else
      ''
        workspace "${n}" {
            open-on-output "${config.local.niri.workspaceOutput}"
        }''
  ) workspaceNames;

  terminal = "${pkgs.kitty}/bin/kitty";
  launcher = "${pkgs.wofi}/bin/wofi --show drun";
  browser = "${pkgs.vivaldi}/bin/vivaldi";
  fileManager = "${pkgs.kdePackages.dolphin}/bin/dolphin";
  # Bare `ranger` so it resolves from PATH to home-manager's wrapped build,
  # which carries the preview tools. The raw ${pkgs.ranger} has none of them.
  fileManagerTui = "${terminal} -e ranger";
in
{
  xdg.configFile."niri/config.kdl".text = ''
    // Generated by home/joshr/niri/niri.nix — edit that, not this file.
    //
    // Colours live in the active theme, swapped by `theme-apply`. niri
    // reloads its config automatically when this include target changes.
    include "${activeDir}/niri.kdl"

    // Displays. Set per host in home/joshr/<host>-niri.nix via
    // local.niri.outputs; nothing here means niri auto-detects.
    ${outputBlocks}

    input {
        keyboard {
            numlock
            xkb {
                layout "us"
            }
            repeat-delay 400
            repeat-rate 40
        }

        touchpad {
            tap
            natural-scroll
            dwt
            accel-profile "adaptive"
            scroll-method "two-finger"
        }

        mouse {
            // Flat profile: no pointer acceleration. Matches the setting
            // carried over from the Plasma config.
            accel-profile "flat"
        }

        // Focus follows the mouse only when it crosses into another window.
        focus-follows-mouse max-scroll-amount="0%"

        // Don't let a misbehaving client warp the cursor.
        warp-mouse-to-focus
    }

    layout {
        gaps 12

        center-focused-column "never"

        preset-column-widths {
            proportion 0.33333
            proportion 0.5
            proportion 0.66667
        }

        default-column-width { proportion 0.5; }

        // waybar is a layer-shell panel, so niri already reserves space for
        // it; struts are only extra outer gaps on top of that.
        struts {
            top 0
            bottom 0
            left 0
            right 0
        }
    }

    // Named workspaces. waybar's niri/workspaces module shows these, and the
    // Mod+<n> binds below jump straight to them.
    //
    // Pinned to an output when local.niri.workspaceOutput is set. niri
    // otherwise creates a workspace on whichever output happens to be
    // focused, so without this the numbered workspaces scatter across
    // displays depending on where you were standing when you first used one.
${workspaceBlocks}

    prefer-no-csd

    screenshot-path "~/Pictures/Screenshots/Screenshot from %Y-%m-%d %H-%M-%S.png"

    hotkey-overlay {
        skip-at-startup
    }

    environment {
        // Hint toolkits toward Wayland backends.
        NIXOS_OZONE_WL "1"
        MOZ_ENABLE_WAYLAND "1"
        QT_QPA_PLATFORM "wayland;xcb"
        QT_WAYLAND_DISABLE_WINDOWDECORATION "1"
        SDL_VIDEODRIVER "wayland"
        _JAVA_AWT_WM_NONREPARENTING "1"
        // Set by niri itself for its own session; declared here so child
        // processes agree on it.
        XDG_CURRENT_DESKTOP "niri"
        XDG_SESSION_TYPE "wayland"
    }

    cursor {
        xcursor-theme "Bibata-Modern-Ice"
        xcursor-size 24
        hide-when-typing
    }

    // X11 apps (Steam, some games, older Electron) go through
    // xwayland-satellite. The NixOS module installs it; this starts it.
    xwayland-satellite {
        path "${bin pkgs.xwayland-satellite}"
    }

    animations {
        slowdown 0.7
    }

    overview {
        zoom 0.5
    }

    // waybar runs as a systemd user service (see waybar.nix) so the theme
    // switcher can restart it; starting it here as well would give two bars.
    spawn-at-startup "${bin niriScripts.wallpaperRestore}"

    // nm-applet is deliberately not started. Its tray icon duplicates the
    // waybar `network` module, and that module's click already opens
    // nm-connection-editor, so the applet added an icon and nothing else.

    // Floating dialogs, pickers and popups.
    window-rule {
        match app-id=r#"^org\.keepassxc\.KeePassXC$"#
        match app-id=r#"^org\.gnome\.Calculator$"#
        match app-id=r#"^Bitwarden$"#
        match title="^Picture-in-Picture$"
        match title="^Open File$"
        match title="^Save File$"
        open-floating true
    }

    // Rounded corners everywhere, matching waybar and wofi.
    window-rule {
        geometry-corner-radius 8
        clip-to-geometry true
    }

    // Games and video players: no rounding, no shadow, and don't let the
    // screen blank on them.
    window-rule {
        match app-id=r#"^steam_app_"#
        match app-id=r#"^gamescope$"#
        match app-id=r#"^mpv$"#
        geometry-corner-radius 0
        clip-to-geometry false
        shadow { off; }
    }

    // Blank the lock screen's own surface out of screencasts.
    layer-rule {
        match namespace="^wofi$"
        shadow { on; }
    }

    binds {
        Mod+Shift+Slash { show-hotkey-overlay; }

        // --- launching -------------------------------------------------
        Mod+Return hotkey-overlay-title="Terminal" { spawn-sh "${terminal}"; }
        Mod+D      hotkey-overlay-title="Applications" { spawn-sh "${launcher}"; }
        Mod+E      hotkey-overlay-title="Files" { spawn-sh "${fileManager}"; }
        Mod+Ctrl+E hotkey-overlay-title="Files (ranger)" { spawn-sh "${fileManagerTui}"; }
        Mod+B      hotkey-overlay-title="Browser" { spawn-sh "${browser}"; }

        // --- session ---------------------------------------------------
        Mod+Escape hotkey-overlay-title="Lock" { spawn "${bin niriScripts.lockSession}"; }
        Mod+Shift+Escape hotkey-overlay-title="Session menu" { spawn "${bin niriScripts.sessionMenu}"; }
        Mod+Shift+E { quit; }
        Ctrl+Alt+Delete { quit; }
        Mod+Shift+I hotkey-overlay-title="Stay awake (toggle)" { spawn "${bin niriScripts.idleInhibit}" "toggle"; }

        // --- theming ---------------------------------------------------
        // Cycle themes, or pick one / a wallpaper from a menu.
        Mod+Shift+T hotkey-overlay-title="Next theme" { spawn "${bin niriScripts.themeCycle}"; }
        Mod+Ctrl+T  hotkey-overlay-title="Choose theme" { spawn "${bin niriScripts.themeMenu}"; }
        Mod+Shift+W hotkey-overlay-title="Choose wallpaper" { spawn "${bin niriScripts.wallpaperMenu}"; }
        Mod+Ctrl+W  hotkey-overlay-title="Random wallpaper" { spawn "${bin niriScripts.wallpaperRandom}"; }

        // --- screenshots -----------------------------------------------
        // Region capture goes through satty for annotation; the plain
        // screen/window captures use niri's own actions, which already know
        // the exact geometry.
        Print              hotkey-overlay-title="Screenshot region" { spawn "${bin niriScripts.screenshot}"; }
        Ctrl+Print         { screenshot-screen; }
        Alt+Print          { screenshot-window; }
        Mod+Shift+S        hotkey-overlay-title="Screenshot region" { spawn "${bin niriScripts.screenshot}"; }

        // --- media / hardware keys -------------------------------------
        XF86AudioRaiseVolume allow-when-locked=true { spawn-sh "${pkgs.wireplumber}/bin/wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.05+ -l 1.0"; }
        XF86AudioLowerVolume allow-when-locked=true { spawn-sh "${pkgs.wireplumber}/bin/wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.05-"; }
        XF86AudioMute        allow-when-locked=true { spawn-sh "${pkgs.wireplumber}/bin/wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"; }
        XF86AudioMicMute     allow-when-locked=true { spawn-sh "${pkgs.wireplumber}/bin/wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"; }

        XF86AudioPlay allow-when-locked=true { spawn "${bin pkgs.playerctl}" "play-pause"; }
        XF86AudioStop allow-when-locked=true { spawn "${bin pkgs.playerctl}" "stop"; }
        XF86AudioPrev allow-when-locked=true { spawn "${bin pkgs.playerctl}" "previous"; }
        XF86AudioNext allow-when-locked=true { spawn "${bin pkgs.playerctl}" "next"; }

        XF86MonBrightnessUp   allow-when-locked=true { spawn "${bin pkgs.brightnessctl}" "--class=backlight" "set" "+5%"; }
        XF86MonBrightnessDown allow-when-locked=true { spawn "${bin pkgs.brightnessctl}" "--class=backlight" "set" "5%-"; }

        // --- window management -----------------------------------------
        Mod+Q repeat=false { close-window; }
        Mod+O repeat=false { toggle-overview; }

        Mod+Left  { focus-column-left; }
        Mod+Down  { focus-window-down; }
        Mod+Up    { focus-window-up; }
        Mod+Right { focus-column-right; }
        Mod+H     { focus-column-left; }
        Mod+J     { focus-window-down; }
        Mod+K     { focus-window-up; }
        Mod+L     { focus-column-right; }

        Mod+Ctrl+Left  { move-column-left; }
        Mod+Ctrl+Down  { move-window-down; }
        Mod+Ctrl+Up    { move-window-up; }
        Mod+Ctrl+Right { move-column-right; }
        Mod+Ctrl+H     { move-column-left; }
        Mod+Ctrl+J     { move-window-down; }
        Mod+Ctrl+K     { move-window-up; }
        Mod+Ctrl+L     { move-column-right; }

        Mod+Home { focus-column-first; }
        Mod+End  { focus-column-last; }

        // --- workspaces -------------------------------------------------
        Mod+Page_Down      { focus-workspace-down; }
        Mod+Page_Up        { focus-workspace-up; }
        Mod+U              { focus-workspace-down; }
        Mod+I              { focus-workspace-up; }
        Mod+Ctrl+Page_Down { move-column-to-workspace-down; }
        Mod+Ctrl+Page_Up   { move-column-to-workspace-up; }

        Mod+1 { focus-workspace "1"; }
        Mod+2 { focus-workspace "2"; }
        Mod+3 { focus-workspace "3"; }
        //Mod+4 { focus-workspace "4"; }
        //Mod+5 { focus-workspace "5"; }

        Mod+Shift+1 { move-column-to-workspace "1"; }
        Mod+Shift+2 { move-column-to-workspace "2"; }
        Mod+Shift+3 { move-column-to-workspace "3"; }
        //Mod+Shift+4 { move-column-to-workspace "4"; }
        //Mod+Shift+5 { move-column-to-workspace "5"; }

        // --- scrolling --------------------------------------------------
        // Mod + scroll moves along the row of windows. niri lays windows out
        // on one horizontal strip, so a vertical scroll mapping to
        // left/right is the natural gesture: spin the wheel and you travel
        // the strip.
        //
        // Wheel and touchpad are bound separately — they're distinct
        // triggers, so binding only WheelScroll* leaves the touchpad dead.
        // No cooldown here: unlike workspace switching, stepping several
        // windows in one flick is the point.
        Mod+WheelScrollDown    { focus-column-right; }
        Mod+WheelScrollUp      { focus-column-left; }
        Mod+WheelScrollRight   { focus-column-right; }
        Mod+WheelScrollLeft    { focus-column-left; }

        Mod+TouchpadScrollDown  { focus-column-right; }
        Mod+TouchpadScrollUp    { focus-column-left; }
        Mod+TouchpadScrollRight { focus-column-right; }
        Mod+TouchpadScrollLeft  { focus-column-left; }

        // Workspaces move to Mod+Shift+scroll, since Mod+scroll now walks
        // windows. Kept on a cooldown so one flick is one workspace.
        Mod+Shift+WheelScrollDown     cooldown-ms=150 { focus-workspace-down; }
        Mod+Shift+WheelScrollUp       cooldown-ms=150 { focus-workspace-up; }
        Mod+Shift+TouchpadScrollDown  cooldown-ms=150 { focus-workspace-down; }
        Mod+Shift+TouchpadScrollUp    cooldown-ms=150 { focus-workspace-up; }

        // Carry the focused column with you.
        Mod+Ctrl+WheelScrollDown    cooldown-ms=150 { move-column-to-workspace-down; }
        Mod+Ctrl+WheelScrollUp      cooldown-ms=150 { move-column-to-workspace-up; }
        Mod+Ctrl+TouchpadScrollDown cooldown-ms=150 { move-column-to-workspace-down; }
        Mod+Ctrl+TouchpadScrollUp   cooldown-ms=150 { move-column-to-workspace-up; }

        // --- monitors ---------------------------------------------------
        // On the letter keys rather than the arrows: Mod+Shift+arrows now
        // resize (see sizing below). Everything else here already mirrors
        // arrows with H/J/K/L, so monitor focus reads the same way.
        Mod+Shift+H { focus-monitor-left; }
        Mod+Shift+L { focus-monitor-right; }

        // Carrying a column across keeps both spellings — Ctrl+Shift+arrows
        // were never claimed by resizing.
        Mod+Shift+Ctrl+Left  { move-column-to-monitor-left; }
        Mod+Shift+Ctrl+Right { move-column-to-monitor-right; }
        Mod+Shift+Ctrl+H     { move-column-to-monitor-left; }
        Mod+Shift+Ctrl+L     { move-column-to-monitor-right; }

        // --- sizing -----------------------------------------------------
        Mod+R       { switch-preset-column-width; }
        Mod+Shift+R { switch-preset-window-height; }
        Mod+F       { maximize-column; }
        Mod+Shift+F { fullscreen-window; }
        Mod+M       { maximize-window-to-edges; }
        Mod+C       { center-column; }
        Mod+Minus   { set-column-width "-10%"; }
        Mod+Equal   { set-column-width "+10%"; }
        Mod+Shift+Minus { set-window-height "-10%"; }
        Mod+Shift+Equal { set-window-height "+10%"; }

        // Resize with the arrows: the direction you press is the direction
        // the window grows. Right/Up enlarge, Left/Down shrink.
        //
        // Width is a *column* property and height a *window* one — that's
        // niri's model, not a slip. A column holding two stacked windows
        // widens as a unit, while Up/Down resize only the focused window
        // within it.
        Mod+Shift+Left  { set-column-width "-10%"; }
        Mod+Shift+Right { set-column-width "+10%"; }
        Mod+Shift+Up    { set-window-height "+10%"; }
        Mod+Shift+Down  { set-window-height "-10%"; }

        Mod+BracketLeft  { consume-or-expel-window-left; }
        Mod+BracketRight { consume-or-expel-window-right; }
        Mod+Comma  { consume-window-into-column; }
        Mod+Period { expel-window-from-column; }

        Mod+V       { toggle-window-floating; }
        Mod+Shift+V { switch-focus-between-floating-and-tiling; }
        Mod+W       { toggle-column-tabbed-display; }

        Mod+Shift+P { power-off-monitors; }
    }
  '';
}
